// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowQuitAnyway() {
  return window['go']['main']['App']['AllowQuitAnyway']();
}

export function ClearDirty() {
  return window['go']['main']['App']['ClearDirty']();
}

export function ClearLastFile() {
  return window['go']['main']['App']['ClearLastFile']();
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveAsFile(arg1) {
  return window['go']['main']['App']['SaveAsFile'](arg1);
}

export function SaveDotFile(arg1) {
  return window['go']['main']['App']['SaveDotFile'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SavePNGFile(arg1) {
  return window['go']['main']['App']['SavePNGFile'](arg1);
}

export function SetDirty() {
  return window['go']['main']['App']['SetDirty']();
}
