// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowQuitAnyway():Promise<void>;

export function ClearDirty():Promise<void>;

export function ClearLastFile():Promise<void>;

export function ForceQuit():Promise<void>;

export function LoadFile():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function SaveAsFile(arg1:string):Promise<void>;

export function SaveDotFile(arg1:string):Promise<void>;

export function SaveFile(arg1:string):Promise<void>;

export function SavePNGFile(arg1:string):Promise<void>;

export function SetDirty():Promise<void>;
