name: Build Wails App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: macos-latest
            platform: darwin/universal
          - os: windows-latest
            platform: windows/amd64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to PATH
        run: echo "${{ runner.temp }}/go/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Linux GUI dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libglib2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libgio2.0-dev \
            libxtst-dev \
            libx11-dev

      - name: Build app
        run: wails build -platform ${{ matrix.platform }}
        working-directory: ./msdl-wails-editor-2GB

      - name: List build output
        run: find ./msdl-wails-editor-2GB/build -type f || true

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: systemigram-editor-windows
          path: msdl-wails-editor-2GB/build/windows/

      - name: Upload macOS binary
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: systemigram-editor-darwin
          path: msdl-wails-editor-2GB/build/darwin/

      - name: Upload Linux binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: systemigram-editor-linux
          path: msdl-wails-editor-2GB/build/bin/