name: Build Wails App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin/universal
          - os: windows-latest
            platform: windows/amd64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to PATH
        run: echo "${{ runner.temp }}/go/bin" >> $GITHUB_PATH

      - name: Build app
        run: wails build -platform ${{ matrix.platform }}
        working-directory: ./msdl-wails-editor-256MB

      - name: List build output
        run: find ./msdl-wails-editor-256MB/build -type f || true

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: systemigram-editor-windows
          path: msdl-wails-editor-256MB/build/windows/

      - name: Upload macOS binary
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: systemigram-editor-darwin
          path: msdl-wails-editor-256MB/build/darwin/